name: LaTeX Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my files
        uses: actions/checkout@v2
      - name: Build chemistry notes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Other Notes/Liang's Notes.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          work_in_root_file_dir: true
      - name: Upload notes
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            Other Notes/Liang's Notes.pdf
